# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  create-package:
    runs-on: ubuntu-latest 
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'                    
          scope: '@hugobernardoni'
          token: ${{ secrets.NPM_ACCESS_TOKEN }}        
      - run: git config --global user.name 'Authority'
      - run: git config --global user.email 'authority@authority.org'
      - run: npm version patch -m "[VERSION] %s"
      - run: git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'          
          # Defaults to the user or organization that owns the workflow file
          scope: '@hugobernardoni'
      
      - run: yarn install --frozen-lockfile   
      - run: yarn build      
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Package creating
        run: |
          echo "Waiting sleep time"
          sleep 10s
  dispatch:
    needs: create-package
    strategy:
      matrix:
        repo: ['hugobernardoni/get-package']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: build
